/**
 * Shape of the compiled rules bundle.
 *
 * The bundle is generated by scripts/build_app_data.py from rules/*.yaml. These
 * types are the contract between that script and this app: if the Python adds or
 * renames a field, `tsc --noEmit` fails here rather than the UI rendering
 * `undefined` in front of a user.
 *
 * Keep them in step with `build()` in scripts/build_app_data.py.
 */

/** Which of the two Flow Simulation animations a pathway plays. */
export type Animation = 'leakage' | 'recovery';

/** Where a pathway ends up. Drives the card's colour treatment. */
export type Terminus = 'recovery' | 'controlled' | 'disposal';

export type PathwayId =
  | 'sell_junkshop'
  | 'barangay_mrf'
  | 'home_compost'
  | 'special_waste_dropoff'
  | 'residual_to_slf';

export interface Pathway {
  label_tl: string;
  label_en: string;
  terminus: Terminus;
}

export interface Price {
  low: number | null;
  high: number | null;
  /** Pre-rendered by the Python so both clients phrase it identically. */
  display: string;
  has_market: boolean;
  confidence: string;
  as_of: string | null;
}

export interface Citation {
  citation: string;
  /** False until the ordinance PDF has actually been retrieved (plan §7.8). */
  verified: boolean;
}

export interface Material {
  class: string;
  /** Junkshop trade names. `local_names[0]` is the display name. */
  local_names: string[];
  pathway: PathwayId;
  animation: Animation;
  price: Price;
  prep_tl: string;
  prep_en: string;
  /** Sachet. Recall is reported separately and the card carries a warning. */
  is_critical_class: boolean;
  /** Nominal price exists but most shops refuse it — glass. */
  often_refused: boolean;
  epr_covered: boolean;
  resin_code: number | null;
  typical_unit_mass_g: number | null;
  citations: Citation[];
  /**
   * The §7.8 gate. While false, guidance may be shown but must NOT be attributed
   * to the Municipality of Cainta.
   */
  presentable_as_official: boolean;
  warnings: string[];
}

export interface OverrideCondition {
  user_flag?: string;
  contaminated?: boolean;
}

export interface Override {
  id: string;
  when: OverrideCondition;
  pathway: PathwayId;
  animation: Animation;
  reason_tl: string;
  reason_en: string;
  /** Replaces the material's prep text when this override fires. */
  prep_tl: string;
  prep_en: string;
}

export interface FlowStage {
  id: string;
  label_tl: string;
  label_en: string;
  detail_tl: string;
  detail_en: string;
  terminal?: boolean;
  verification?: string;
  note?: string;
}

export interface FlowPath {
  label_tl: string;
  label_en: string;
  stages: FlowStage[];
}

export interface Flow {
  /** Always 'schematic' until OSM waterway geometry replaces it (plan §2.2). */
  kind: string;
  verification: string;
  caveat: string;
  leakage: FlowPath;
  recovery: FlowPath;
}

export interface Verification {
  legal_sources_total: number;
  legal_sources_verified: number;
  phase1_gate_met: boolean;
  verified_shops: number;
  phase2_gate_met: boolean;
}

export interface RulesBundle {
  generated_from: string[];
  schema_version: number;
  status: string;
  updated_on: string;
  verification: Verification;
  pathways: Record<string, Pathway>;
  materials: Material[];
  overrides: Override[];
  flow: Flow;
  barangays: string[];
}

/** A resolved answer to "where does this go in Cainta?". */
export interface Resolution {
  material: Material;
  pathway: Pathway;
  pathwayId: PathwayId;
  animation: Animation;
  override: Override | null;
  /** Prep text after any override substitution. */
  prepTl: string;
}

/** The scan wizard's in-progress selection. */
export interface Selection {
  materialClass: string;
  flags: string[];
  contaminated: boolean;
}
